# Generated by Django 5.2 on 2025-04-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('website', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('notes', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vault_User',
            fields=[
                ('username', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('is_superuser', models.BooleanField()),
            ],
        ),
    ]
