# Generated by Django 5.2 on 2025-04-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault_user',
            name='user_first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='vault_user',
            name='user_last_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
