# Generated by Django 5.2 on 2025-05-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_vault_user_user_first_name_vault_user_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault_user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
