# Generated by Django 5.2 on 2025-05-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_vault_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault_user',
            name='user_last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
