# Generated by Django 5.2 on 2025-05-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0004_alter_vault_user_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='name',
            field=models.TextField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='credential',
            name='password',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='credential',
            name='username',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='credential',
            name='website',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vault_user',
            name='password',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vault_user',
            name='user_first_name',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='vault_user',
            name='user_last_name',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vault_user',
            name='username',
            field=models.TextField(max_length=14, primary_key=True, serialize=False),
        ),
    ]
